#!/usr/bin/env bash
# bundle.sh — build a single, dependency-free statusline.sh.
#
# The documented install is "point Claude Code at one file". Cloning a repo to
# get a status line is friction, and a released single file is also immutable,
# which a branch URL is not. This produces that file: every library, every
# segment, and every theme inlined.
#
# The bundle sets SL_BUNDLED=1, which makes statusline.sh skip loading lib/,
# and overrides theme resolution to read the embedded definitions.
set -euo pipefail

SL_REPO=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
OUT=${1:-dist/statusline.sh}
VERSION=$(cat "${SL_REPO}/version.txt" 2>/dev/null || printf 'dev')

mkdir -p "$(dirname "$OUT")"

# strip_header <file> — drop the shebang so it does not land mid-file.
strip_header() {
  sed '1{/^#!/d;}' "$1"
}

{
  printf '#!/usr/bin/env bash\n'
  printf '#\n'
  printf '# statuslines %s — single-file build\n' "$VERSION"
  printf '# https://github.com/williamzujkowski/statuslines\n'
  printf '#\n'
  printf '# Generated by scripts/bundle.sh. Do not edit: edit the sources and rebuild.\n'
  printf '#\n'
  printf '# Install:\n'
  printf '#   "statusLine": { "type": "command", "command": "bash ~/.claude/statusline.sh" }\n'
  printf '#\n\n'
  printf 'SL_BUNDLED=1\n'
  printf 'SL_VERSION=%s\n\n' "$VERSION"

  for lib in core colors theme render; do
    printf '# ─── lib/%s.sh ───────────────────────────────────────────────\n' "$lib"
    strip_header "${SL_REPO}/lib/${lib}.sh"
    printf '\n'
  done

  # Segments are defined up front. sl_segment_load short-circuits on an
  # already-defined function, so it never looks for the files.
  for seg in "${SL_REPO}"/lib/segments/*.sh; do
    name=${seg##*/}
    printf '# ─── segment: %s ───────────────────────────────────────────\n' "${name%.sh}"
    strip_header "$seg"
    printf '\n'
  done

  # Themes, embedded as text and fed to the same parser the on-disk path uses,
  # so a bundled theme cannot drift from its source.
  printf '# ─── embedded themes ─────────────────────────────────────────\n'
  # shellcheck disable=SC2016 # $1 is literal: it belongs to the generated function
  printf '_sl_theme_text() {\n  case "$1" in\n'
  for theme in "${SL_REPO}"/themes/*.conf; do
    name=${theme##*/}
    name=${name%.conf}
    printf '    %s)\n      cat <<%s\n' "$name" "'SL_THEME_EOF'"
    cat "$theme"
    printf 'SL_THEME_EOF\n      ;;\n'
  done
  printf '    *) return 1 ;;\n  esac\n}\n\n'

  cat <<'OVERRIDE'
# A bundled build has no themes directory. A user theme on disk still wins, so
# someone can override a shipped theme without rebuilding.
sl_theme_resolve() {
  local name=$1 dir
  case "$name" in
    "" | *[!a-zA-Z0-9_-]*) return 1 ;;
  esac
  for dir in \
    "${XDG_CONFIG_HOME:-$HOME/.config}/statuslines/themes" \
    "$HOME/.claude/statuslines/themes"; do
    if [ -r "$dir/$name.conf" ]; then
      printf '%s' "$dir/$name.conf"
      return 0
    fi
  done
  _sl_theme_text "$name" >/dev/null 2>&1 || return 1
  printf 'bundled:%s' "$name"
}

sl_theme_load() {
  case "$1" in
    # Process substitution, not a pipe: a pipeline runs sl_theme_parse in a
    # subshell, so every SL_THEME_* it sets would be discarded on return.
    bundled:*) sl_theme_parse < <(_sl_theme_text "${1#bundled:}") ;;
    *)
      [ -r "$1" ] || return 1
      sl_theme_parse <"$1"
      ;;
  esac
}

OVERRIDE

  printf '# ─── statusline.sh ───────────────────────────────────────────\n'
  strip_header "${SL_REPO}/statusline.sh"
} >"$OUT"

chmod +x "$OUT"

# A bundle that does not run is worse than no bundle, so prove it here rather
# than discovering it in a release.
if ! out=$(printf '{"workspace":{"current_dir":"/tmp/x"},"model":{"display_name":"Test"},"context_window":{"used_percentage":42,"context_window_size":200000}}' |
  COLUMNS=120 STATUSLINE_THEME=default bash "$OUT" 2>/dev/null) || [ -z "$out" ]; then
  printf 'bundle.sh: the generated bundle failed to render\n' >&2
  exit 1
fi

printf 'Built %s (%s lines, %s bytes)\n' "$OUT" "$(wc -l <"$OUT" | tr -d ' ')" "$(wc -c <"$OUT" | tr -d ' ')"
printf 'Smoke render: %s\n' "$out"
